CCOPTS= -Wall -fsigned-char -std=c++17 -stdlib=libc++
COPTS= -Wall -fsigned-char
#COPTS=-O4 -ggdb -Wall -fsigned-char
#COPTS=-O4 -Wall -fsigned-char -DHACK
#COPTS=-O2 -pg -Wall -fsigned-char
#COPTS=-g -Wall -fsigned-char
# -g causes gdb to run into "heuristic fence-posts"
#LIBS=-lfastm
LIBS=-L. -lm
